on:
  push:
    branches:
      - main

jobs:
  build:
    name: jsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "cat package.json"
        run: cat ./package.json
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: "cat package.json"
        run: cat ./package.json
      - name: install node v12
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 12
      - name: npm install
        run: npm install
      - name: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
